name: PHP Composer

on:
  push:

  pull_request:

  schedule:
    - cron: '30 4 * * *'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer and Dependencies
        run: curl -s http://getcomposer.org/installer | php && php composer.phar self-update && php composer.phar install

      - name: Tests
        run: php composer.phar test

      - name: Coding Style
        run: php composer.phar cs-check
